#! /usr/bin/python
#coding=utf-8

import re
flist = [
'/usr/local/projects/python/数据/三门/r10.txt',
'/usr/local/projects/python/数据/三门/r11.txt',
'/usr/local/projects/python/数据/三门/r12.txt',
'/usr/local/projects/python/数据/三门/r13.txt',
'/usr/local/projects/python/数据/三门/r14.txt',
'/usr/local/projects/python/数据/三门/r15.txt',
'/usr/local/projects/python/数据/三门/r16.txt',
'/usr/local/projects/python/数据/三门/r17.txt',
'/usr/local/projects/python/数据/三门/r18.txt',
'/usr/local/projects/python/数据/三门/r19.txt',
'/usr/local/projects/python/数据/三门/r6.txt',
'/usr/local/projects/python/数据/三门/r7.txt',
'/usr/local/projects/python/数据/三门/r8.txt',
'/usr/local/projects/python/数据/三门/r9.txt',
'/usr/local/projects/python/数据/三门/三门r20.txt',
'/usr/local/projects/python/数据/临海/10.txt',
'/usr/local/projects/python/数据/临海/11.txt',
'/usr/local/projects/python/数据/临海/12.txt',
'/usr/local/projects/python/数据/临海/13.txt',
'/usr/local/projects/python/数据/临海/14.txt',
'/usr/local/projects/python/数据/临海/15.txt',
'/usr/local/projects/python/数据/临海/16.txt',
'/usr/local/projects/python/数据/临海/17.txt',
'/usr/local/projects/python/数据/临海/18.txt',
'/usr/local/projects/python/数据/临海/19.txt',
'/usr/local/projects/python/数据/临海/20.txt',
'/usr/local/projects/python/数据/临海/6.txt',
'/usr/local/projects/python/数据/临海/7.txt',
'/usr/local/projects/python/数据/临海/8.txt',
'/usr/local/projects/python/数据/临海/9.txt',
'/usr/local/projects/python/数据/仙居/10.txt',
'/usr/local/projects/python/数据/仙居/11.txt',
'/usr/local/projects/python/数据/仙居/12.txt',
'/usr/local/projects/python/数据/仙居/13.txt',
'/usr/local/projects/python/数据/仙居/14.txt',
'/usr/local/projects/python/数据/仙居/15.txt',
'/usr/local/projects/python/数据/仙居/16.txt',
'/usr/local/projects/python/数据/仙居/17.txt',
'/usr/local/projects/python/数据/仙居/18.txt',
'/usr/local/projects/python/数据/仙居/19.txt',
'/usr/local/projects/python/数据/仙居/20.txt',
'/usr/local/projects/python/数据/仙居/6.txt',
'/usr/local/projects/python/数据/仙居/7.txt',
'/usr/local/projects/python/数据/仙居/8.txt',
'/usr/local/projects/python/数据/仙居/9.txt',
'/usr/local/projects/python/数据/大陈岛/10.txt',
'/usr/local/projects/python/数据/大陈岛/11.txt',
'/usr/local/projects/python/数据/大陈岛/12.txt',
'/usr/local/projects/python/数据/大陈岛/13.txt',
'/usr/local/projects/python/数据/大陈岛/14.txt',
'/usr/local/projects/python/数据/大陈岛/15.txt',
'/usr/local/projects/python/数据/大陈岛/16.txt',
'/usr/local/projects/python/数据/大陈岛/17.txt',
'/usr/local/projects/python/数据/大陈岛/18.txt',
'/usr/local/projects/python/数据/大陈岛/19.txt',
'/usr/local/projects/python/数据/大陈岛/20.txt',
'/usr/local/projects/python/数据/大陈岛/6.txt',
'/usr/local/projects/python/数据/大陈岛/7.txt',
'/usr/local/projects/python/数据/大陈岛/8.txt',
'/usr/local/projects/python/数据/大陈岛/9.txt',
'/usr/local/projects/python/数据/天台/r11.txt',
'/usr/local/projects/python/数据/天台/r12.txt',
'/usr/local/projects/python/数据/天台/r13.txt',
'/usr/local/projects/python/数据/天台/r14.txt',
'/usr/local/projects/python/数据/天台/r15.txt',
'/usr/local/projects/python/数据/天台/r16.txt',
'/usr/local/projects/python/数据/天台/r18.txt',
'/usr/local/projects/python/数据/天台/r19.txt',
'/usr/local/projects/python/数据/天台/r20.txt',
'/usr/local/projects/python/数据/天台/天台r10.txt',
'/usr/local/projects/python/数据/天台/天台r6.txt',
'/usr/local/projects/python/数据/天台/天台r7.txt',
'/usr/local/projects/python/数据/天台/天台r8.txt',
'/usr/local/projects/python/数据/天台/天台r9.txt',
'/usr/local/projects/python/数据/洪家/10.txt',
'/usr/local/projects/python/数据/洪家/11.txt',
'/usr/local/projects/python/数据/洪家/12.txt',
'/usr/local/projects/python/数据/洪家/13.txt',
'/usr/local/projects/python/数据/洪家/14.txt',
'/usr/local/projects/python/数据/洪家/15.txt',
'/usr/local/projects/python/数据/洪家/16.txt',
'/usr/local/projects/python/数据/洪家/17.txt',
'/usr/local/projects/python/数据/洪家/18.txt',
'/usr/local/projects/python/数据/洪家/19.txt',
'/usr/local/projects/python/数据/洪家/20.txt',
'/usr/local/projects/python/数据/洪家/6.txt',
'/usr/local/projects/python/数据/洪家/7.txt',
'/usr/local/projects/python/数据/洪家/8.txt',
'/usr/local/projects/python/数据/洪家/9.txt',
'/usr/local/projects/python/数据/温岭/10.txt',
'/usr/local/projects/python/数据/温岭/11.txt',
'/usr/local/projects/python/数据/温岭/12.txt',
'/usr/local/projects/python/数据/温岭/13.txt',
'/usr/local/projects/python/数据/温岭/14.txt',
'/usr/local/projects/python/数据/温岭/15.txt',
'/usr/local/projects/python/数据/温岭/16.txt',
'/usr/local/projects/python/数据/温岭/17.txt',
'/usr/local/projects/python/数据/温岭/18.txt',
'/usr/local/projects/python/数据/温岭/19.txt',
'/usr/local/projects/python/数据/温岭/20.txt',
'/usr/local/projects/python/数据/温岭/6.txt',
'/usr/local/projects/python/数据/温岭/7.txt',
'/usr/local/projects/python/数据/温岭/8.txt',
'/usr/local/projects/python/数据/温岭/9.txt',
'/usr/local/projects/python/数据/玉环/10.txt',
'/usr/local/projects/python/数据/玉环/11.txt',
'/usr/local/projects/python/数据/玉环/12.txt',
'/usr/local/projects/python/数据/玉环/13.txt',
'/usr/local/projects/python/数据/玉环/14.txt',
'/usr/local/projects/python/数据/玉环/15.txt',
'/usr/local/projects/python/数据/玉环/16.txt',
'/usr/local/projects/python/数据/玉环/17.txt',
'/usr/local/projects/python/数据/玉环/18.txt',
'/usr/local/projects/python/数据/玉环/19.txt',
'/usr/local/projects/python/数据/玉环/20.txt',
'/usr/local/projects/python/数据/玉环/6.txt',
'/usr/local/projects/python/数据/玉环/7.txt',
'/usr/local/projects/python/数据/玉环/8.txt',
'/usr/local/projects/python/数据/玉环/9.txt']
ofile = open('/usr/local/projects/python/allinone.txt', 'w')

pattern = re.compile(r'年')
for fr in flist:
    for txt in open(fr, 'r'):
	str = txt.readline()
        match = pattern.match(str)
        if not match:
            ofile.write(txt)
ofile.close()	

